version: '2'

networks:
  basic:

services:

  world:
    container_name: world
    image: video-server-stream
    ports:
      - "8099:80"
    volumes:
      - ./app/go/world:/go/src/app:rw
    networks:
      - basic
